=== etux/mpango/mpango-game-core/src/main/resources/technologies/technology.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- types -->

  <!-- elements -->
  <xs:element name="techname" type="xs:string"/>
  <xs:element name="requires" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="unitsenabled" type="xs:string"/>
  <xs:element name="buildingsenabled" type="xs:string"/>
  <xs:element name="effects" type="xs:string"/>
  <xs:element name="cost" type="xs:positiveInteger"/>

  <!-- complex elements -->
  <!-- basic technology -->
  <xs:element name="technology" >
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="techname"/>
        <xs:element ref="description"/>
        <xs:element ref="requires" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="unitsenabled" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="buildingsenabled" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="effects" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="cost"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
   
  <!-- root (all the technologies) -->
  <xs:element name="treetech">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="technology" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== etux/mpango/mpango-game-parent/mpango-game-core/src/test/resources/technologies/technology.xml
<?xml version="1.0" encoding="utf-8"?>
<treetech xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="technology.xsd">
  <technology>
    <techname>stone</techname>
    <description>...</description>
    <unitsenabled>stone axe</unitsenabled>
    <buildingsenabled>Sandstone</buildingsenabled>
    <effects>+att</effects>
    <cost>10</cost>
  </technology>
  <technology>
    <techname>fire</techname>
    <description>Fire is a great succes, now people can eat more easy so they can live longer. You learn how to dry wood improving your weapons.</description>
    <requires>stone</requires>
    <requires>religion</requires>
    <unitsenabled>wood lancers</unitsenabled>
    <unitsenabled>flame trapper</unitsenabled>
    <effects>+hp</effects>
    <cost>10</cost>
  </technology>
  
</treetech>
